FROM maven:3-amazoncorretto-17 AS extensions

WORKDIR /app

COPY pom.xml .
COPY src src

RUN mvn package

FROM quay.io/keycloak/keycloak:23.0 AS builder

# Install any custom providers here

COPY --from=extensions /app/target/keycloak-theme-additional-info-extension.jar /opt/keycloak/providers/

RUN /opt/keycloak/bin/kc.sh build


FROM quay.io/keycloak/keycloak:23.0

COPY --from=builder /opt/keycloak/ /opt/keycloak/

ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
